### ISSUE TITLE
Specify TODOs

### ISSUE THREAD

**Issue by sairajsawant** [mangoblogger/MangoBlogger_HTML_CSS_JavaScript_Code#1]
I am willing to contribute. Kindly specify some todos for the mangoblogger.com site!

**Comment by mangoblogger** [comment]
Thank you for your comment and interest! This is a good idea. We have added the to-dos issues. 

Feel free to add any more comments as you have them.

**Comment by sairajsawant** [comment]
Can you similarly open up todos for your Android Application?
